package testPack;

import org.junit.Test;
import org.junit.runner.RunWith;

import presentation.IHM;

import command.Command;
import command.MarquerMesure;
import command.MarquerTemps;
import controleur.Controleur;

import junit.framework.TestCase;
import model.MM;
import model.MMImpl;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;
import org.mockito.runners.*;


/**
 * The class <code>MMImplTest</code> contains tests for the class {@link
 * <code>MMImpl</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 12/27/13 12:59 PM
 *
 * @author boussad
 *
 * @version $Revision$
 */
@RunWith(MockitoJUnitRunner.class)
public class MMImplTest  {

	private MMImpl moteur; 

	
	// Mocker les deux commandes : 
	private MarquerTemps marquertemp; 
	private MarquerMesure marquermesure;
	
	public MMImplTest(){

		moteur  = new MMImpl(null);
		// mocker les deux methodes de marquer temp et marquer mesure 
	  
		marquertemp = mock(MarquerTemps.class);
		marquermesure = mock(MarquerMesure.class);
		
	}
	
	

	@Test 
	public void testClick(){
		moteur.setMarquerTemps(marquertemp);
		moteur.setMarquerMesure(marquermesure);
		
		//  par default nbTemp par mesure = 1
		moteur.click();
		verify(marquertemp).executer();
	    verify(marquermesure).executer();  

	}
	
	
	@Test
	public void testTempsParMesure(){

		moteur = new MMImpl(null);
		moteur.setNbTempsParMesure(4);
		assertEquals(moteur.getNbTempsParMesure(),4);
	}
	
	public void testSetEnMarch(){
		moteur = new MMImpl(null);
		moteur.setEnMarche(true);
		assertTrue(moteur.getEnMarche());
		
		moteur.setEnMarche(false);
		assertFalse(moteur.getEnMarche());
	}
	
	
	
	
	
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = unitTestPack
 * package.sourceFolder = metronome/src/test/java
 * superclassType = junit.framework.TestCase
 * testCase = MMImplTest
 * testClassType = model.MMImpl
 */